from pandera.pandas import DataFrameSchema, Column, Check
# from datetime import datetime

schema = DataFrameSchema(
    columns={
        "cust_id": Column(
            dtype=str,
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
        ),
        "day": Column(
            dtype=int,
            # checks=[
            #     Check.greater_than_or_equal_to(min_value=1, raise_warning=True, ignore_na=False),
            #     Check.less_than_or_equal_to(max_value=31, raise_warning=True, ignore_na=False),
            # ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "month": Column(
            dtype=int,
            # checks=[
            #     Check.greater_than_or_equal_to(min_value=1, raise_warning=True, ignore_na=False),
            #     Check.less_than_or_equal_to(max_value=12, raise_warning=True, ignore_na=False),
            # ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "year": Column(
            dtype=int,
            # checks=[
            #     Check.greater_than_or_equal_to(min_value=2000, raise_warning=True, ignore_na=False),
            #     Check.less_than_or_equal_to(max_value=datetime.now().year, raise_warning=True, ignore_na=False),
            # ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "item_name": Column(
            dtype=str,
            checks=None,
            nullable=False,
            unique=False,
            coerce=False,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "sku": Column(
            dtype=str,
            checks=None,
            nullable=False,
            unique=False,
            coerce=False,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "cost": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(min_value=0, raise_warning=True, ignore_na=False),
                Check.less_than_or_equal_to(max_value=1_000_000, raise_warning=True, ignore_na=False),
            ],
            nullable=False,
            unique=False,
            coerce=False,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "currency": Column(
            dtype=str,
            checks=None,
            nullable=False,
            unique=False,
            coerce=False,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "purchase_channel": Column(
            dtype=str,
            checks=None,
            nullable=False,
            unique=False,
            coerce=False,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
    },
    coerce=True,
    strict=False,
    ordered=False,
    report_duplicates="all",
    unique_column_names=False,
    add_missing_columns=False,
    name="Set2_Purchases_Input",
    title="Sample set 2 purchases input",
    description="Schema for input file for dataframe: Purchases",
)
