from pandera.pandas import DataFrameSchema, Column
# from datetime import datetime

schema = DataFrameSchema(
    columns={
        "person_id": Column(
            dtype=str,
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
        ),
        "purchase_date": Column(
            dtype=str,
            nullable=True,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "item_desc": Column(
            dtype=str,
            nullable=True,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "item_no": Column(
            dtype=str,
            checks=None,
            nullable=True,
            unique=False,
            coerce=False,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "price_usd": Column(
            dtype="str",
            checks=None,
            nullable=True,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "quantity": Column(
            dtype=str,
            checks=None,
            nullable=True,
            unique=False,
            coerce=False,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
    },
    coerce=True,
    strict=False,
    ordered=False,
    report_duplicates="all",
    unique_column_names=True,
    add_missing_columns=False,
    name="Set1_Purchases_Input",
    title="Sample set 1 purchases input",
    description="Schema for input file for dataframe: Purchases",
)
